PersonalWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('service/', include('service.urls', namespace='service')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('contact/', views.ContactView.as_view(), name= 'contact'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name= 'home'),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('portfolio/', views.PortfolioView.as_view(), name= 'portfolio'),
    path('detail/<int:portfolio_id>', views.PortfolioDetailView.as_view(), name= 'detail'),
]

resume/urls.py
from django.urls import path
from . import views

app_name = 'resume'
urlpatterns = [
    path('resume/', views.ResumeView.as_view(), name= 'resume'),
]

service/urls.py
from django.urls import path
from . import views

app_name = 'service'
urlpatterns = [
    path('service/', views.ServiceView.as_view(), name= 'service'),
    path('detail/<int:service_id>', views.ServiceDetailView.as_view(), name= 'detail'),
]

contact/models.py
from django.db import models

# Create your models here.

class ContactInfo(models.Model):
    email = models.EmailField()
    phone_number = models.CharField(max_length=11)
    address = models.TextField()

    def __str__(self):
        return f'{self.phone_number} - {self.email}'


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = models.CharField(max_length=11)
    messages = models.TextField()

    def __str__(self):
        return f'{self.email} - {self.messages}'

home/models.py
from django.db import models

# Create your models here.
class PersonalInfo(models.Model):
    name = models.CharField(max_length=200)
    job = models.CharField(max_length=200)
    description = models.TextField()
    resume = models.FileField(upload_to='resume')

    def __str__(self):
        return self.name

portfolio/models.py
from django.db import models

# Create your models here.

class Portfolio(models.Model):
    banner = models.ImageField(upload_to="portfolio/banner")
    title = models.CharField(max_length=100)
    image1 =  models.ImageField(upload_to="portfolio/image", null = True, blank=True)
    image2 =  models.ImageField(upload_to="portfolio/image", null = True, blank=True)
    image3 =  models.ImageField(upload_to="portfolio/image", null = True, blank=True)
    image4 =  models.ImageField(upload_to="portfolio/image", null = True, blank=True)
    description = models.TextField()
    summery = models.TextField()
    designer = models.TextField()

    def __str__(self):
        return self.title

resume/models.py
from django.db import models

# Create your models here.
class Skills(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

class Education(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

service/models.py
from django.db import models

# Create your models here.
class Services(models.Model):
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='services/images/')
    body = models.TextField()

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

contact/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Contact, ContactInfo
from .forms import ContactForm
from django.contrib import messages
# Create your views here.

class ContactView(View):
    form_class = ContactForm
    template_name = 'contact/contact.html'

    def get(self, request):
        info = ContactInfo.objects.all()
        form = self.form_class
        return render(request, self.template_name, {'form': form,
                                                    'info': info})
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Contact.objects.create(first_name=cd['first_name'],
                                   last_name=cd['last_name'],
                                   phone_number=cd['phone_number'],
                                   email=cd['email'],
                                   messages=cd['messages'])
            messages.success(request, 'پیغام شما با موفقیت ارسال شد!', 'success')
            return redirect('home:home')
        else:
            messages.error(request, 'مجدد تلاش کنید!', 'error')
            return render(request, self.template_name, {'form': form})

home/views.py
from django.shortcuts import render, redirect
from django.views import View
import os
from django.http import FileResponse
from django.contrib import messages
from .models import PersonalInfo

# Create your views here.

class HomeView(View):
    def get(self, request):
        personal = PersonalInfo.objects.all()
        file_path = os.path.join('media', 'resume.pdf')
        if os.path.exists(file_path):
            with open(file_path, 'rb') as f:
                response = FileResponse(f, as_attachment=True, filename='resume.pdf')
                return response
        else:
            messages.error(request, 'بارگذاری انجام نشد ، مجدد تلاش کنید!', 'error')
            # return redirect('home:home')
        return render(request, 'home/home.html', {'personal': personal})

portfolio/views.py
from django.shortcuts import render
from django.views import View
from .models import Portfolio

# Create your views here.
class PortfolioView(View):
    template_name = 'portfolio/portfolio.html'

    def get(self, request):
        portfolio = Portfolio.objects.all()
        return render(request,self.template_name,{'portfolio': portfolio} )


class PortfolioDetailView(View):
    template_name = 'portfolio/detail.html'

    def get(self, request, portfolio_id):
        detail = Portfolio.objects.get(id=portfolio_id)
        return render(request, self.template_name, {'detail': detail})

resume/views.py
from django.shortcuts import render
from django.views import View
from .models import Skills, Education

# Create your views here.
class ResumeView(View):
    def get(self, request):
        skill = Skills.objects.all()
        education = Education.objects.all()
        return render(request, 'resume/resume.html',
                      {'skill': skill,
                       'education': education})

service/views.py
from django.shortcuts import render
from django.views import View
from .models import Services

# Create your views here.
class ServiceView(View):
    def get(self,request):
        services = Services.objects.all()
        return render(request, 'services/service.html',
                      {'services': services})


class ServiceDetailView(View):
    def get(self, request, service_id):
        detail = Services.objects.get(id=service_id)
        return render(request, 'services/detail.html',
                      {'detail': detail})

contact/templates/contact/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for infos in info %}
    {{ infos.email }}
    {{ infos.phone_number }}
    {{ infos.address }}
{% endfor %}

    <form method="post" action="">
        {% csrf_token %}
        {{ form.first_name }}
        {{ form.last_name }}
        {{ form.phone_number }}
        {{ form.email }}
        {{ form.messages }}
        <input type="submit" value="Send">
    </form>
</body>
</html>

home/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1> this is home page</h1>
    {% for personals in personal %}
        {{ personals.name }}
        {{ personals.age }}
        {{ personals.description }}
    {% endfor %}
    <a href="{% url 'home:home' %}" class="btn btn-primary">دانلود رزومه</a>
</body>
</html>

portfolio/templates/portfolio/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <img src="{{ detail.banner.url }}" alt="banner">
    {{ detail.title }}
    <img src="{{ detail.image1.url }}" alt="image">
    <img src="{{ detail.image2.url }}" alt="image">
    <img src="{{ detail.image3.url }}" alt="image">
    <img src="{{ detail.image4.url }}" alt="image">
    {{ detail.description }}
    {{ detail.summery }}
    {{ detail.designer }}
</body>
</html>

portfolio/templates/portfolio/portfolio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for portfolios in portfolio %}
        <img src="{{ portfolios.banner.url }}" alt="banner">
        <a href="{% url 'portfolio:detail' portfolios.id %}">{{ portfolios.title }}</a>


    {% endfor %}
</body>
</html>

resume/templates/resume/resume.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for skills in skill %}
        {{ skills.title }}
        {{ skills.description}}
    {% endfor %}

    {% for educations in education %}
        {{ educations.title }}
        {{ educations.description}}
    {% endfor %}
</body>
</html>

service/templates/services/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <img src="{{ detail.image.url }}" alt="banner">
    {{ detail.body }}
</body>
</html>

service/templates/services/service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

    {% for service in services %}
        <a href="{% url 'service:detail' service.id %}">{{ service.name }}</a>
        {{ service.body }}
    {% endfor %}

</body>
</html>